Enable jenkins enviroment to run failed test cases
edx/edx-app-test pull request #61
Opened 2020-09-10 09:09 UTC by bilalawan321

2020-09-10 09:11 UTC, bilalawan321 commented
@nedo i have tested on AWS UI and its working fine and now i have to test it on master, 
Can you please Review this PR. ?

2020-09-10 13:07 UTC, nedo commented
@bilalawan321 please get this pass through pep8 and pylint first. `continuous-integration/travis-ci/pr` job should also Pass.

2020-09-10 18:18 UTC, bilalawan321 commented
@nedo all pep8 and pylint issues have been fixed, and **Travis** job is also passing successfully.

2020-09-11 05:03 UTC, bilalawan321 commented
@farhan-arshad-dev can you review this PR ?

2020-09-16 09:19 UTC, farhan-arshad-dev requested changes

2020-09-16 09:19 UTC, farhan-arshad-dev commented on tests/common/globals.py
> +        self.set_target_environments()
IMO: `setup_global_environment` is more appropriate.

2020-09-16 09:19 UTC, farhan-arshad-dev commented on tests/common/globals.py
> +        elif self.jenkins is True:
no need to check `self.jenkins is True`.   use else statement

2020-09-16 09:19 UTC, farhan-arshad-dev commented on tests/conftest.py
> +    # extra.append(pytest_html.extras.html(html))
if these comments are unnecessary please remove them.

2020-09-16 09:35 UTC, bilalawan321 commented on tests/conftest.py
> +    # extra.append(pytest_html.extras.html(html))
@farhan-arshad-dev  this test case is failing on jenkins master job, 
i will fix this test case when i will fix all other failed test cases, in a saperate PR.

2020-09-16 12:13 UTC, farhan-arshad-dev approved these changes

2020-09-16 12:44 UTC, merged