Fix failed test cases after 2.23 release
edx/edx-app-test pull request #62
Opened 2020-10-11 19:46 UTC by bilalawan321

2020-10-12 04:49 UTC, bilalawan321 commented
@farhan-arshad-dev can you please review this PR. ?

2020-10-16 14:15 UTC, farhan-arshad-dev requested changes

2020-10-16 14:15 UTC, farhan-arshad-dev commented on tests/android/pages/android_elements.py
> +register_validate_spinner_error_textview = 'org.edx.mobile:id/input_auto_complete_error'
`register_validate_auto_complete_error_textview` is more appropriate.
use the following statment to make the prevent from the `pylint` error.
```
register_validate_auto_complete_error_textview = 'org.edx.mobile:id/' \
                                           'input_auto_complete_error'
```

2020-10-16 14:19 UTC, bilalawan321 commented on tests/android/pages/android_elements.py
> +register_country_textview = 'org.edx.mobile:id/input_auto_complete'
fixed

2020-10-16 14:19 UTC, bilalawan321 commented on tests/android/pages/android_elements.py
> +register_validate_spinner_error_textview = 'org.edx.mobile:id/input_auto_complete_error'
fixed

2020-10-16 14:31 UTC, bilalawan321 commented
@farhan-arshad-dev i have fixed your reviews, can you check now. ?

2020-10-16 14:45 UTC, farhan-arshad-dev approved these changes

2020-10-16 14:50 UTC, merged