Course Dashboard screen automation code
edx/edx-app-test pull request #63
Opened 2020-11-04 13:23 UTC by bilalawan321

Following features have been implemented:
Verify that Course Dashboard screen will show following contents:
Header contents
Back icon  
Specific "<course name>" as Title 
Share icon
Verify that user should be able to go back by clicking Back icon
Verify that user should be able to view these Course contents:
Course Image 
Course Name
Course Provider
Course Ending date 
Last accessed(if any) 
Course Content
Verify on tapping "Videos" tab will load Videos screen
Verify on tapping "Discussion" tab will load Discussions screen
Verify on tapping "Dates" tab will load Dates screen
Verify on tapping "Resources" tab will load Resources screen

2020-11-04 13:46 UTC, bilalawan321 commented
@farhan-arshad-dev  can you please review this PR. ?

2020-11-11 11:18 UTC, farhan-arshad-dev requested changes

2020-11-11 11:18 UTC, farhan-arshad-dev commented on tests/android/tests/test_android_course_dashboard.py
> +            assert android_course_dashboard_page.get_all_text_views()[0].text in course_name
I think this check is the same as [Line# 74](https://github.com/edx/edx-app-test/pull/63/files#diff-f2dfa6c077917093a5c018d76616404dfb38a140608b298ebb36a27e21379ee6R74) both are checking the title of the page.

2020-11-11 14:44 UTC, bilalawan321 commented on tests/common/strings.py
> +WHATS_NEW_DONE = 'DONE'
fixed

2020-11-11 14:49 UTC, bilalawan321 commented on tests/android/tests/test_android_course_dashboard.py
> +            assert android_course_dashboard_page.get_all_text_views()[0].text in course_name
@farhan-arshad-dev, line 69 checks the header title of page, while line 74 checks the "course name" which is shown on course image, i have updated function name for clarity.

2020-11-11 14:50 UTC, bilalawan321 commented
@farhan-arshad-dev  can you plz check now, ?

2020-11-12 07:38 UTC, farhan-arshad-dev requested changes

2020-11-12 07:38 UTC, farhan-arshad-dev commented on tests/android/tests/test_android_course_dashboard.py
> +            assert android_course_dashboard_page.get_all_text_views()[0].text in course_name
better to add doc string for Line# 74

2020-11-12 07:38 UTC, farhan-arshad-dev commented on tests/android/tests/test_android_course_dashboard.py
> +            assert android_course_dashboard_page.get_all_text_views()[0].text in course_name
Also one is screen title and the second is course name/title

2020-11-12 08:00 UTC, farhan-arshad-dev approved these changes

2020-11-12 08:04 UTC, merged