Android course topics
edx/edx-app-test pull request #64
Opened 2020-11-12 08:24 UTC by bilalawan321

###Description
- LEARNER-7992(https://openedx.atlassian.net/browse/LEARNER-7992)

Followings features/stories will be implemented:
Verify that Course Topics screen will show following Header contents,
Back icon
Specific "<Topic name>" as Title
Verify that user should be able to go back by clicking Back icon
Verify that user should be able to view these on Every Topic in the list:
Topic name
Topic icon
download icon to video (if available)
Verify that on Clicking any topic Specific resource screen should be loaded successfully

2020-11-12 08:26 UTC, bilalawan321 commented
@farhan-arshad-dev  can you please review this PR ?

2020-11-12 10:15 UTC, farhan-arshad-dev requested changes

2020-11-12 10:15 UTC, farhan-arshad-dev commented on tests/android/tests/test_android_course_subsection.py
> +        if topic_name:
deserve doc-string, like verify screen title.

2020-11-12 10:25 UTC, bilalawan321 commented on tests/common/strings.py
> +COURSE_SUBSECTION_VIDEO_ROW_TEXT = 'Lecture Module 1: Introductions'
fixed

2020-11-12 10:25 UTC, bilalawan321 commented on tests/common/globals.py
> +        self.jenkins = False
pushed it mistakenly. 
fixed

2020-11-12 10:27 UTC, bilalawan321 commented on tests/android/pages/android_elements.py
> +course_dashboard_course_title = 'org.edx.mobile:id/course_detail_name'
fixed

2020-11-12 10:29 UTC, bilalawan321 commented on tests/android/tests/test_android_course_subsection.py
> +        if topic_name:
fixed

2020-11-13 10:01 UTC, farhan-arshad-dev approved these changes

2020-11-13 10:10 UTC, merged